import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { AlertTriangle } from "lucide-react";

interface AboutStaticExplanationsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function AboutStaticExplanationsModal({ isOpen, onClose }: AboutStaticExplanationsModalProps) {
  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>About This Explanation</DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <p>
            This explanation was written and verified by our subject matter experts rather than generated by AI. We use expert-authored content for calculations, regulatory topics, and other complex areas where absolute accuracy is essential for your exam preparation.
          </p>
          <p>
            Your feedback helps us identify which topics benefit most from expert review. Use the thumbs up/down buttons to let us know if this explanation was helpful.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}